### ISSUE TITLE
The csproblem has double $ prefix

### ISSUE THREAD

**Issue by taneltm** [YourDad07/CP-Bot#2]
At least in the documentation, the `csproblem` command has a double $ prefix. None of the other commands have a $$ prefix. I'm guessing it's a typo.
![image](https://user-images.githubusercontent.com/5690464/130404053-5d11b200-d6a7-4d1c-9a8c-bce77658cf84.png)

**Comment by SalmanAd01** [comment]
Thanks, I've Fixed It.
