### ISSUE TITLE
Run and input commands need to be capitalized?

### ISSUE THREAD

**Issue by taneltm** [YourDad07/CP-Bot#3]
In the documentation, the `$Run` and it's `$Input` commands are capitalized. Is that necessary? - Other commands don't have capitalized first letters.
![image](https://user-images.githubusercontent.com/5690464/130404348-b0df692a-b55f-4a86-803c-9f7bbc963dc4.png)

**Comment by SalmanAd01** [comment]
Thank, i've Fixed it.
