### ISSUE TITLE
Specify code to run within code blocks

### ISSUE THREAD

**Issue by taneltm** [YourDad07/CP-Bot#4]
Example of how the run command could work:
~~~
$run
```python
a = input('Enter a number: ')
b = input('Enter a number: ')
x = float(a) + float(b)
print(x)
```
$input
```
3
5
```
~~~

1. Multiple inputs could be given
2. A single command for C and Python is easier to remember for users
3. The code would be formatted and the syntax can be taken from the code block
4. `$input` can be used within the code
5. When users have a link in their code, discord will ignore it and not create a preview embed.
6. Syntax highlighting while typing the code
    ![image](https://user-images.githubusercontent.com/5690464/130406738-acc5fb9d-9b3c-41d0-bb30-63ddf4fbd27d.png)
7. The $input part could actually be removed. The second code tag could always be considered as the input.

**Comment by SalmanAd01** [comment]
Thanks For The Suggestion. I've fixed It.
